// AUTH TYPES
export const GET_ERRORS = "AUTH/GET_ERRORS";
export const USER_LOADING = "AUTH/USER_LOADING";
export const SET_CURRENT_USER = "AUTH/SET_CURRENT_USER";

// PRODUCTS TYPES
export const GET_OUR_PRODUCTS = "PRODUCTS/GET_OUR_PRODUCTS";
export const GET_DATE_LAST_UPDATE =
  "PRODUCTS/GET_DATE_LAST_UPDATE";

export const GET_SHOPS_DATA = "PRODUCTS/GET_SHOPS_DATA";

export const SET_DATA_LOADING = "PRODUCTS/SET_DATA_LOADING";
